SET LINES 160
SET PAGES 9999
COL USERNAME FOR A17
COL ACCOUNT_STATUS FOR A18
COL HOST_NAME FOR A35
COL PROFILE FOR A15
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON

var v_owner varchar2(30);

exec :v_owner := '&1';

SELECT INSTANCE_NAME AS INS_NAME,
       HOST_NAME, 
       USERNAME, 
       DEFAULT_TABLESPACE AS DEFAULT_TBS,
       ACCOUNT_STATUS, 
       TO_CHAR(CREATED, 'DD/MM/YYYY HH24:MI') AS CREATED, 
       PROFILE
  FROM DBA_USERS, V$INSTANCE
 WHERE USERNAME like upper(:v_owner)
 ORDER BY USERNAME
;

--exit